generic:
  deployTimeout: "3m"

pam:
  provider: "singleconnect"
  url: "https://pam.megafon.ru"
  aapmToken: ""
  secrets:
    - name: {{PROJECT_NAME}}_postgres_db_password
      secretPath: "/MegaFon/Common/Data-Analytics/preprod/{{PROJECT_NAME}}/postgres_db_password"
      property: password
    - name: {{PROJECT_NAME}}_postgres_db_username
      secretPath: "/MegaFon/Common/Data-Analytics/preprod/{{PROJECT_NAME}}/postgres_db_password"
      property: username
    - name: {{PROJECT_NAME}}_redis_db_password
      secretPath: "/MegaFon/Common/Data-Analytics/preprod/{{PROJECT_NAME}}/redis_db_password"
      property: password
    - name: {{PROJECT_NAME}}_redis_db_username
      secretPath: "/MegaFon/Common/Data-Analytics/preprod/{{PROJECT_NAME}}/redis_db_password"
      property: username

deployment:
  replicaCount: 1
  container:
    registry: docker-middle-preprod-local.unixrepo.megafon.ru
    imagePullPolicy: Always
    env:
      - name: ENV
        value: "PREPROD"
      - name: APP_NAME
        value: "{{PROJECT_NAME}}"
      - name: APP_ENV
        value: "preprod"
      - name: LOG_LEVEL
        value: "info"

      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: {{PROJECT_NAME}}-secrets-from-pam
            key: {{PROJECT_NAME}}_postgres_db_username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{PROJECT_NAME}}-secrets-from-pam
            key: {{PROJECT_NAME}}_postgres_db_password
      - name: DB_HOST
        value: "{{PG_HOST}}"
      - name: DB_NAME
        value: "{{PG_DB}}"
      - name: DB_PORT
        value: "5432"

      - name: REDIS_HOST
        value: "{{REDIS_HOST}}"
      - name: REDIS_PORT
        value: "6379"

      - name: CH_HOST
        value: "{{CH_HOST}}"
      - name: CH_DB
        value: "{{CH_DB}}"
